package logic;

public enum Operations {
    ADD_SOUVENIR,
    ADD_MANUFACTURER,
    WATCH_SOUVENIRS,
    WATCH_MANUFACTURERS,
    DISPLAY_SOUVENIRS_BY_MANUFACTURER,
    DISPLAY_SOUVENIRS_BY_COUNTRY,
    DISPLAY_MANUFACTURERS_BY_PRICE,
    DISPLAY_MANUFACTURERS_WITH_THEY_SOUVENIRS,
    DISPLAY_MANUFACTURERS_BY_SOUVENIR_AND_YEAR,
    DISPLAY_SOUVENIRS_BY_YEAR,
    REMOVE,
    SAVE,
    LOAD,
    EXIT

}
